### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by djstrong** [cognitum-octopus/cognipy#37]
Providing path to non-existing encnl file the error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.6/site-packages/cognipy/ontology.py", line 104, in __init__
    modalCheck, passParamsAsCnl, stop_on_error)
  File "venv/lib/python3.6/site-packages/cognipy/interop.py", line 71, in cognipy_call
    raise translate_exception(json.loads(js))
Exception: [

  "IllegalArgumentException",

  {

    "ClassName": "java.lang.IllegalArgumentException",

    "Message": "URI is not absolute",

    "Data": null,

    "InnerException": null,

    "HelpURL": null,

    "StackTraceString": "  at CogniPy.CogniPySvr.Load (CogniPy.ReferenceManager+WhatToLoad whatToLoad, System.String contentToLoad, CogniPy.CNL.DL.Paragraph impliAst, System.Boolean throwOnException, System.Boolean loadAnns, System.Boolean materialize, System.Boolean modalChecker) [0x00057] in <f8783c48f78341ba843524fd57b41eb3>:0 \n  at CogniPy.CogniPySvr.LoadCnl (System.String filename, CogniPy.CNL.DL.Paragraph impliAst, System.Boolean throwOnException, System.Boolean loadAnns, System.Boolean materialize, System.Boolean modalChecker) [0x00000] in <f8783c48f78341ba843524fd57b41eb3>:0 \n  at CogniPy.CogniPySvr.LoadCnl (System.String filename, System.Boolean loadAnnotations, System.Boolean materialize, System.Boolean modalChecker, System.Boolean throwOnError) [0x00000] in <f8783c48f78341ba843524fd57b41eb3>:0 \n  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)\n  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 ",

    "RemoteStackTraceString": null,

    "RemoteStackIndex": 0,

    "ExceptionMethod": null,

    "HResult": -2146233088,

    "Source": "CogniPyLib",

    "$0": {

      "$0": {

        "type": "java.lang.IllegalArgumentException, IKVM.OpenJDK.Core, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58",

        "sig": null

      },

      "$1": {

        "$0": {

          "type": "java.lang.RuntimeException, IKVM.OpenJDK.Core, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58",

          "sig": null

        },

        "$1": {

          "$0": {

            "type": "java.lang.Exception, IKVM.OpenJDK.Core, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58",

            "sig": null

          },

          "$1": {

            "$0": {

              "type": "java.lang.Throwable, IKVM.OpenJDK.Core, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58",

              "sig": null

            },

            "$1": "Ljava/lang/Throwable;",

            "$2": "Ljava/lang/String;",

            "$3": "[Ljava/lang/StackTraceElement;",

            "$4": "Ljava/util/List;",

            "$5": null,

            "$data": "FAFyASgAE2phdmEubGFuZy5UaHJvd2FibGXVxjUnOXe4ywMABEwABWNhdXNlARBMAA1kZXRhaWxNZXNzYWdlAQ1bAApzdGFja1RyYWNlARdMABRzdXBwcmVzc2VkRXhjZXB0aW9ucwIA"

          },

          "$data": "FAFyASAAE2phdmEubGFuZy5FeGNlcHRpb27Q/R8+GjscxAIAAAEA"

        },

        "$data": "FAFyAScAGmphdmEubGFuZy5SdW50aW1lRXhjZXB0aW9unl8GRwo0g+UCAAABAA=="

      },

      "$data": "FAFyAS8AImphdmEubGFuZy5JbGxlZ2FsQXJndW1lbnRFeGNlcHRpb261iXPTfWaPvAIAAAEA"

    },

    "$2": "URI is not absolute",

    "$3": [],

    "$4": [],

    "$data": "CgUA"

  }

]
```
To reproduce (on Ubuntu):
```from cognipy.ontology import Ontology
onto = Ontology("cnl/file","nonexisting.encnl")
```

**Comment by kaplan196883** [comment]
Fixed
